wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.11
    t:
      2:
      - 1
      3:
      - 2
      4: 3.7.11
      5: 0.11.2
      8:
      - 1
      - 3
      - 5
